routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//use Illuminate\Routing\Route;
use Illuminate\Support\Facades\Route;

Route::get('/', function () {
    return view('welcome');
});

Route::patch('entries/{entry}/approve', 'EntryController@approve')->name('entries.approve');
Route::patch('entries/{entry}/reject', 'EntryController@reject')->name('entries.reject');

Route::resource('entries', 'EntryController');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Entry.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Entry extends Model
{

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'entry', 'comment', 'user_id', 'status_id'
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'status_id' => 'string',
    ];

    public function author() {
        return $this->belongsTo('App\User', 'user_id', 'id');
    }

    public function status() {
        return $this->belongsTo('App\Status', 'status_id', 'id');
    }
}

app/Role.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Role extends Model
{

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'id', 'label'
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'id' => 'string',
    ];

    //public $incrementing = false;

    CONST ADMIN = 'admin';
    CONST GUEST = 'guest';
    /**
     *
     */
    public function users()
    {
        return $this->belongsToMany('App\User');
    }
}

app/Status.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Status extends Model
{
    CONST STATUS_APPROVE = 'approve';
    CONST STATUS_REJECT = 'reject';
    CONST STATUS_DRAFT = 'draft';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'id', 'label'
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'id' => 'string',
    ];

    //public $incrementing = false;

    public function entries()
    {
        return $this->hasMany('App\Entry', 'status_id', 'id');
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    /**
     *
     */
    public function roles()
    {
        return $this->belongsToMany('App\Role');
    }

    /**
     * Returns whether user has role
     */
    public function hasRole($role)
    {
        foreach($this->roles as $r) {
            if($r->id == $role) {
                return TRUE;
            }
        }
        return FALSE;
    }

    public function entries()
    {
        return $this->hasMany('App\Entry', 'user_id', 'id');
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/EntryController.php
<?php

namespace App\Http\Controllers;

use App\Entry;
use App\Status;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class EntryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $this->authorize('create', Entry::class);
        $entries = Entry::all();
        return view('entries.index', compact('entries'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $this->authorize('create', Entry::class);
        return view('entries.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name'=>'required',
            'entry'=>'required',
            'comment'=>'required'
        ]);

        $entry = new Entry([
            'name' => $request->get('name'),
            'entry' => $request->get('entry'),
            'comment' => $request->get('comment'),
            'user_id' => Auth::user()->id,
            'status_id' => Status::STATUS_DRAFT
        ]);
        $entry->save();
        return redirect('/entries')->with('success', 'Entry saved!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $entry = Entry::find($id);
        $this->authorize('update', $entry);
        return view('entries.edit', compact('entry'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'name'=>'required',
            'entry'=>'required',
            'comment'=>'required'
        ]);

        $contact = Entry::find($id);
        $contact->name =  $request->get('name');
        $contact->entry = $request->get('entry');
        $contact->comment = $request->get('comment');
        $contact->save();

        return redirect('/entries')->with('success', 'Entry updated!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $entry = Entry::find($id);
        $this->authorize('delete', $entry);
        $entry->delete();

        return redirect('/entries')->with('success', 'Entry deleted!');
    }

    /**
     * Approve the Entry
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function approve($id) {
        $entry = Entry::find($id);

        $this->authorize('update', $entry);
        $entry->status()->associate(Status::STATUS_APPROVE);
        $entry->save();
        return redirect('/entries')->with('success', 'Entry approved!');
    }

    /**
     * Reject the Entry
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function reject($id) {
        $entry = Entry::find($id);

        $this->authorize('update', $entry);
        $entry->status()->associate(Status::STATUS_REJECT);
        $entry->save();
        return redirect('/entries')->with('success', 'Entry rejected!');
    }
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }
}

resources/views/base.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>GuestBook | by Shiva</title>
  <link href="{{ asset('css/app.css') }}" rel="stylesheet" type="text/css" />
</head>
<body>
  <div class="container">
    @yield('main')
  </div>
  <script src="{{ asset('js/app.js') }}" type="text/js"></script>
</body>
</html>

resources/views/entries/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
  <div class="row">
    <div class="col-sm-8 offset-sm-2">
      <h1>Add a entry</h1>
      <div>
        @if ($errors->any())
          <div class="alert alert-danger">
            <ul>
            @foreach ($errors->all() as $error)
              <li>{{ $error }}</li>
            @endforeach
          </ul>
          </div><br />
        @endif
        <form method="post" action="{{ route('entries.store') }}">
        @csrf
          <div class="form-group">
            <label for="name">Name:</label>
            <input type="text" class="form-control" name="name"/>
          </div>

          <div class="form-group">
            <label for="entry">Entry:</label>
            <textarea class="form-control" name="entry" id="entry" rows="3"></textarea>
          </div>

          <div class="form-group">
            <label for="comment">Comment:</label>
            <textarea class="form-control" name="comment" id="comment" rows="3"></textarea>
          </div>

          <button type="submit" class="btn btn-primary-outline">Add entry</button>
        </form>
      </div>
    </div>
  </div>
</div>
@endsection

resources/views/entries/edit.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
  <div class="row">
    <div class="col-sm-8 offset-sm-2">
      <h1 class="display-3">Update a entry</h1>
      @if ($errors->any())
        <div class="alert alert-danger">
          <ul>
          @foreach ($errors->all() as $error)
            <li>{{ $error }}</li>
          @endforeach
          </ul>
        </div>
        <br />
      @endif
      <form method="post" action="{{ route('entries.update', $entry->id) }}">
      @method('PATCH')
      @csrf
        <div class="form-group">
          <label for="name">Name:</label>
          <input type="text" class="form-control" name="name" value={{ $entry->name }} />
        </div>

        <div class="form-group">
          <label for="entry">Entry:</label>
          <textarea class="form-control" name="entry" id="entry" rows="3">{{ $entry->entry }}</textarea>
        </div>

        <div class="form-group">
          <label for="comment">Comment:</label>
          <textarea class="form-control" name="comment" id="comment" rows="3">{{ $entry->comment }}</textarea>
        </div>
        <button type="submit" class="btn btn-primary">Update</button>
      </form>
    </div>
  </div>
</div>
@endsection

resources/views/entries/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
  <div class="row">
    <div class="col-sm-12">
      @if(session()->get('success'))
        <div class="alert alert-success">
          {{ session()->get('success') }}
        </div>
      @endif
    </div>
  </div>
  <div class="row">
    <div class="col-sm-12">
      <h1>Guest Entries</h1>
	  @auth
      <div>
        <a href="{{ route('entries.create')}}" class="btn btn-primary">New entry</a>
      </div>
      <table class="table table-striped">
        <thead>
          <tr>
            <td>ID</td>
            <td>Name</td>
            <td>Entry</td>
            <td>Comment</td>
            <td>Status</td>
            <td colspan = 4>Actions</td>
          </tr>
        </thead>
        <tbody>
          @foreach($entries as $entry)
          @can('view', $entry)
          <tr>
            <td>{{$entry->id}}</td>
            <td>{{$entry->name}} {{$entry->last_name}}</td>
            <td>{{$entry->entry}}</td>
            <td>{{$entry->comment}}</td>
            <td>{{$entry->status->label}}</td>
			@can('delete', $entry)
			@if($entry->status->label == 'Draft')
            <td>
              <a href="{{ route('entries.edit',$entry->id)}}" class="btn btn-primary">Edit</a>
            </td>
            <td>
              <form action="{{ route('entries.approve', $entry->id)}}" method="post">
                @csrf
                @method('PATCH')
                <button class="btn btn-primary" type="submit">Approve</button>
              </form>
            </td>
            <td>
              <form action="{{ route('entries.reject', $entry->id)}}" method="post">
                @csrf
                @method('PATCH')
                <button class="btn btn-primary" type="submit">Reject</button>
              </form>
            </td>
            <td>
              <form action="{{ route('entries.destroy', $entry->id)}}" method="post">
                @csrf
                @method('DELETE')
                <button class="btn btn-danger" type="submit">Delete</button>
              </form>
            </td>
			@endif
            @endcan
          </tr>
          @endcan
          @endforeach
        </tbody>
      </table>
	  @endauth
    <div>
  </div>
</div>
@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Guestbook') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                   Hello {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>